/* ExtraLogic.com — puzzle banks. Add items to expand; daily rotation is automatic. */
window.XL_RIDDLES = [
  { q: "What has keys but can't open locks?", a: "A piano", k: ["piano", "keyboard"] },
  { q: "The more of them you take, the more you leave behind. What are they?", a: "Footsteps", k: ["footstep", "steps"] },
  { q: "What gets wetter the more it dries?", a: "A towel", k: ["towel"] },
  { q: "I have cities, but no houses; forests, but no trees; water, but no fish. What am I?", a: "A map", k: ["map"] },
  { q: "What can travel around the world while staying in a corner?", a: "A stamp", k: ["stamp"] },
  { q: "A man pushes his car to a hotel and tells the owner he's bankrupt. Why?", a: "He's playing Monopoly", k: ["monopoly"] },
  { q: "What has a neck but no head?", a: "A bottle", k: ["bottle", "shirt"] },
  { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", a: "The letter M", k: ["m", "letter m"] },
  { q: "If you have me, you want to share me. If you share me, you haven't got me. What am I?", a: "A secret", k: ["secret"] },
  { q: "What number do you get when you multiply all of the numbers on a telephone keypad?", a: "Zero", k: ["0", "zero"], e: "The keypad includes 0." },
  { q: "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How many cents does the ball cost?", a: "5 cents", k: ["5", "five", "0.05"], e: "Ball = x, bat = x + 1.00, so 2x + 1.00 = 1.10 → x = 0.05." },
  { q: "If it takes 5 machines 5 minutes to make 5 widgets, how many minutes would it take 100 machines to make 100 widgets?", a: "5 minutes", k: ["5", "five"], e: "Each machine makes one widget in 5 minutes." },
  { q: "A lily pad patch doubles in size every day. It covers the lake in 48 days. On which day did it cover half the lake?", a: "Day 47", k: ["47"], e: "It doubles from half to full on the last day." },
  { q: "What 5-letter word becomes shorter when you add two letters to it?", a: "Short", k: ["short"], e: "Short + er = shorter." },
  { q: "What belongs to you, but other people use it more than you do?", a: "Your name", k: ["name"] },
  { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "A candle", k: ["candle"] },
  { q: "What has many teeth but can't bite?", a: "A comb", k: ["comb", "zipper", "saw"] },
  { q: "What can you catch but not throw?", a: "A cold", k: ["cold", "breath", "glimpse"] },
  { q: "Mary's father has five daughters: Nana, Nene, Nini, Nono. What is the fifth daughter's name?", a: "Mary", k: ["mary"] },
  { q: "What has one eye but can't see?", a: "A needle", k: ["needle", "storm", "hurricane"] },
  { q: "How many months have 28 days?", a: "All 12", k: ["12", "twelve", "all"], e: "Every month has at least 28 days." },
  { q: "What goes up but never comes down?", a: "Your age", k: ["age"] },
  { q: "A rooster lays an egg on top of a sloped roof. Which way does it roll?", a: "Nowhere — roosters don't lay eggs", k: ["rooster", "dont", "don't", "no egg", "nowhere", "doesnt"] },
  { q: "What is always in front of you but can't be seen?", a: "The future", k: ["future"] },
  { q: "Forward I am heavy, but backward I am not. What am I?", a: "Ton", k: ["ton"], e: "Ton backward is 'not'." },
  { q: "I shave every day, but my beard stays the same. Who am I?", a: "A barber", k: ["barber"] },
  { q: "What runs, but never walks; has a mouth, but never talks; has a bed, but never sleeps?", a: "A river", k: ["river"] },
  { q: "Two fathers and two sons go fishing. They catch three fish and each gets one. How?", a: "Grandfather, father and son", k: ["grandfather", "three people", "3 people", "grandpa"] },
  { q: "What word is spelled incorrectly in every dictionary?", a: "Incorrectly", k: ["incorrectly"] },
  { q: "You see a boat full of people, yet there isn't a single person on board. How?", a: "They're all married", k: ["married"] }
];

window.XL_SEQUENCES = [
  { q: "2, 4, 8, 16, ?", o: ["24", "30", "32", "34"], a: 2, e: "Each term doubles." },
  { q: "1, 1, 2, 3, 5, 8, ?", o: ["11", "12", "13", "15"], a: 2, e: "Fibonacci: add the previous two." },
  { q: "3, 6, 11, 18, 27, ?", o: ["36", "38", "40", "35"], a: 1, e: "Differences are 3, 5, 7, 9, 11." },
  { q: "1, 4, 9, 16, 25, ?", o: ["30", "34", "36", "49"], a: 2, e: "Perfect squares: 6² = 36." },
  { q: "2, 3, 5, 7, 11, 13, ?", o: ["15", "17", "19", "16"], a: 1, e: "Prime numbers." },
  { q: "100, 50, 25, 12.5, ?", o: ["6.25", "6", "7.5", "5"], a: 0, e: "Halve each time." },
  { q: "1, 8, 27, 64, ?", o: ["100", "125", "128", "81"], a: 1, e: "Cubes: 5³ = 125." },
  { q: "5, 10, 20, 35, 55, ?", o: ["75", "80", "85", "90"], a: 1, e: "Differences grow by 5: 5, 10, 15, 20, 25." },
  { q: "A, C, F, J, O, ?", o: ["T", "U", "S", "V"], a: 1, e: "Letter jumps of +2, +3, +4, +5, +6: O + 6 = U." },
  { q: "Z, X, V, T, ?", o: ["S", "R", "Q", "P"], a: 1, e: "Skip one letter backward." },
  { q: "1, 3, 7, 15, 31, ?", o: ["47", "62", "63", "64"], a: 2, e: "Double and add 1 (2ⁿ − 1)." },
  { q: "7, 14, 28, 56, ?", o: ["84", "102", "112", "114"], a: 2, e: "Doubling." },
  { q: "0, 1, 3, 6, 10, 15, ?", o: ["20", "21", "22", "25"], a: 1, e: "Triangular numbers: add 6." },
  { q: "81, 27, 9, 3, ?", o: ["0", "1", "1.5", "2"], a: 1, e: "Divide by 3." },
  { q: "2, 6, 12, 20, 30, ?", o: ["40", "42", "44", "36"], a: 1, e: "n(n+1): 6 × 7 = 42." },
  { q: "J, F, M, A, M, J, J, ?", o: ["A", "S", "O", "J"], a: 0, e: "First letters of the months: August." },
  { q: "O, T, T, F, F, S, S, ?", o: ["N", "E", "T", "S"], a: 1, e: "One, Two, Three… Eight." },
  { q: "4, 9, 19, 39, 79, ?", o: ["119", "149", "159", "158"], a: 2, e: "Double and add 1." },
  { q: "1, 2, 6, 24, 120, ?", o: ["240", "600", "720", "144"], a: 2, e: "Factorials: 6! = 720." },
  { q: "11, 13, 17, 19, 23, ?", o: ["25", "27", "29", "31"], a: 2, e: "Primes continue: 29." },
  { q: "10, 9, 7, 4, 0, ?", o: ["-4", "-5", "-6", "-3"], a: 1, e: "Subtract 1, 2, 3, 4, 5." },
  { q: "3, 9, 27, 81, ?", o: ["162", "243", "324", "108"], a: 1, e: "Powers of 3." },
  { q: "B, D, G, K, P, ?", o: ["U", "V", "W", "T"], a: 1, e: "Jumps +2, +3, +4, +5, +6: P + 6 = V." },
  { q: "1, 11, 21, 1211, 111221, ?", o: ["312211", "1112221", "122111", "311221"], a: 0, e: "Look-and-say: 'three 1s, two 2s, one 1'." }
];

window.XL_LOGIC = [
  { q: "On an island, knights always tell the truth and knaves always lie. A says: \"We are both knaves.\" What are A and B?", o: ["Both knights", "A knight, B knave", "A knave, B knight", "Both knaves"], a: 2, e: "A can't be a knight (he'd be lying). So A is a knave and the statement is false, so B must be a knight." },
  { q: "A says: \"At least one of us is a knave.\" What are A and B?", o: ["A knight, B knave", "A knave, B knight", "Both knights", "Both knaves"], a: 0, e: "If A were a knave, the statement would be true — impossible. So A is a knight, and at least one is a knave: B." },
  { q: "All bloops are razzies. All razzies are lazzies. Are all bloops definitely lazzies?", o: ["Yes", "No", "Cannot be determined"], a: 0, e: "Transitive syllogism: bloops ⊂ razzies ⊂ lazzies." },
  { q: "Some cats are black. Some black things are cars. Therefore some cats are cars. Is this valid?", o: ["Valid", "Invalid"], a: 1, e: "Undistributed middle: the black cats and the black cars can be different things." },
  { q: "If it rains, the street is wet. The street is wet. Did it rain?", o: ["Yes, definitely", "Not necessarily", "No, definitely not"], a: 1, e: "Affirming the consequent. A street sweeper could have wet it." },
  { q: "If it rains, the street is wet. The street is NOT wet. What follows?", o: ["It rained", "It did not rain", "Nothing follows"], a: 1, e: "Modus tollens: not-Q, therefore not-P." },
  { q: "You have two coins that total 30 cents. One of them is not a nickel. What are they?", o: ["Two 15¢ coins", "A quarter and a nickel", "Three dimes", "Impossible"], a: 1, e: "One is not a nickel (the quarter) — the other one is." },
  { q: "Three boxes are all labelled wrong: 'Apples', 'Oranges', 'Mixed'. You may pick one fruit from one box. Which box do you pick from to fix every label?", o: ["Apples", "Oranges", "Mixed", "You need two picks"], a: 2, e: "The 'Mixed' box holds a single type. Its fruit tells you that box, and the other two follow." },
  { q: "Which statement is the logical negation of \"All swans are white\"?", o: ["No swans are white", "Some swans are not white", "All swans are black", "Some swans are white"], a: 1, e: "¬∀x P(x) ≡ ∃x ¬P(x)." },
  { q: "Alice is taller than Bob. Bob is taller than Cara. Dan is shorter than Cara. Who is the second shortest?", o: ["Alice", "Bob", "Cara", "Dan"], a: 2, e: "Order: Alice > Bob > Cara > Dan." },
  { q: "A family has two children. At least one is a boy. What's the probability both are boys?", o: ["1/2", "1/3", "1/4", "2/3"], a: 1, e: "Possible cases: BB, BG, GB, and only BB counts, so 1/3." },
  { q: "Monty Hall: you pick door 1, the host opens door 3 (a goat). Should you switch to door 2?", o: ["Switching wins 2/3 of the time", "It's 50/50", "Staying is better"], a: 0, e: "Your first pick wins 1/3 of the time. The host's reveal moves the other 2/3 onto the remaining door." },
  { q: "\"Everyone who studies passes. Sam passed.\" Therefore Sam studied. Which fallacy is this?", o: ["Straw man", "Affirming the consequent", "Ad hominem", "False dilemma"], a: 1, e: "P→Q and Q does not give you P." },
  { q: "\"Either you support this plan or you want the company to fail.\" What fallacy is this?", o: ["Slippery slope", "False dilemma", "Circular reasoning", "Red herring"], a: 1, e: "It pretends only two options exist." },
  { q: "A clock shows 3:15. What is the angle between the hour and minute hands?", o: ["0°", "7.5°", "15°", "22.5°"], a: 1, e: "The hour hand moves 0.5° per minute: 90 + 7.5 = 97.5°, and the minute hand is at 90°." },
  { q: "Among 8 identical-looking balls, one is heavier. What is the minimum number of balance weighings that guarantees you find it?", o: ["1", "2", "3", "4"], a: 1, e: "Split 3-3-2. Each weighing divides the candidates into three groups." },
  { q: "B says: \"A is a knave.\" A says: \"B and I are the same type.\" What are they?", o: ["A knight, B knight", "A knave, B knight", "A knight, B knave", "Both knaves"], a: 1, e: "If A were a knight, B would be a knight too, but then B's claim would be false. So A is a knave, B tells the truth, and A's claim (same type) is correctly false." },
  { q: "How many times a day do a clock's hour and minute hands overlap?", o: ["24", "22", "23", "12"], a: 1, e: "11 times every 12 hours." },
  { q: "If no A are B, and some C are A, then:", o: ["Some C are not B", "No C are B", "All C are B", "Some B are C"], a: 0, e: "The C's that are A cannot be B." },
  { q: "A snail climbs 3 m up a 10 m wall each day and slips 2 m each night. On which day does it reach the top?", o: ["Day 7", "Day 8", "Day 10", "Day 9"], a: 1, e: "After 7 days it's at 7 m. On day 8 it climbs to 10 m before slipping." }
];
